import {DEFAULT_WATCH,DEFAULT_POLICY,SOURCE_REGISTRY,indicators,recommend,buildPositions,sectorWeights,marketRegime} from './core.js';
const K='srvn:'; const $=s=>document.querySelector(s); const clone=x=>structuredClone(x);
const get=(k,d)=>{try{const v=localStorage.getItem(K+k);return v?JSON.parse(v):clone(d)}catch{return clone(d)}};
const set=(k,v)=>localStorage.setItem(K+k,JSON.stringify(v)); const id=()=>crypto.randomUUID();
const fmt=(n,d=2)=>n==null||!Number.isFinite(+n)?'—':new Intl.NumberFormat('vi-VN',{maximumFractionDigits:d}).format(+n);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let S={watch:get('watch',DEFAULT_WATCH),policy:get('policy',DEFAULT_POLICY),tx:get('tx',[]),cash:get('cash',[]),sources:get('sources',[]),signals:get('signals',[]),evidence:get('evidence',[]),journal:get('journal',[]),market:get('market',{}),index:get('index',null),health:get('health',null),intel:get('intel',null),last:get('last',null)};
function save(){for(const k of ['watch','policy','tx','cash','sources','signals','evidence','journal'])set(k,S[k])}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function cash(){return S.cash.reduce((a,x)=>a+(+x.amount||0),0)} function pos(){return buildPositions(S.tx,S.market)} function wgt(){return sectorWeights(pos(),cash())}
function recs(){const e=Object.fromEntries(pos().map(p=>[p.symbol,p.avgCost])),w=wgt();return S.watch.map(x=>recommend(x,S.market[x.symbol],S.policy,e[x.symbol],w[x.sector])).sort((a,b)=>(b.score??-1)-(a.score??-1))}
function regime(){return marketRegime(S.index,Object.values(S.market))}
async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
async function quote(symbol){const key=symbol.replace(/[^A-Z0-9]/gi,'_');for(const url of [`./data/${key}.json`]){try{const x=await json(url);if(x&&Array.isArray(x.points)){x.indicators=indicators(x.points||[]);return x}}catch{}}return{symbol,price:null,points:[],indicators:indicators([]),error:'Chưa có dữ liệu'}}
async function refresh(){const b=$('#refreshBtn');if(b){b.disabled=true;b.textContent='Đang cập nhật…'}try{const syms=[...new Set(S.watch.map(x=>x.symbol))];const [all,h,i]=await Promise.all([Promise.all(['^VNINDEX',...syms].map(quote)),json('./data/health.json').catch(e=>({ok:false,checks:[{name:'health',ok:false,error:e.message}]})),json('./data/intel.json').catch(e=>({ok:false,error:e.message}))]);S.index=all[0];S.market=Object.fromEntries(all.slice(1).map(x=>[x.symbol,x]));S.health=h;S.intel=i;S.last=Date.now();for(const k of ['index','market','health','intel','last'])set(k,S[k]);journal();alerts();render();toast('Đã cập nhật dữ liệu snapshot')}finally{if(b){b.disabled=false;b.textContent='Cập nhật ngay'}}}
function journal(){for(const r of recs()){const p=S.journal.find(x=>x.symbol===r.symbol);if(!p||p.action!==r.action||Math.abs((p.score??0)-(r.score??0))>=5||Date.now()-p.timestamp>3600000)S.journal.unshift({...r,provider:S.market[r.symbol]?.provider||'unknown'})}S.journal=S.journal.slice(0,1500);set('journal',S.journal)}
function alerts(){const a=recs().filter(r=>r.riskSeverity>=70);if('Notification'in window&&Notification.permission==='granted')for(const r of a){const k=`a:${r.symbol}:${r.riskState}`;if(!sessionStorage.getItem(k)){new Notification(`Stock Radar: ${r.symbol}`,{body:`${r.riskState} • ${r.riskSeverity}`});sessionStorage.setItem(k,'1')}}}
function cls(a){return a?.includes('BUY')?'good':a?.includes('EXIT')||a==='AVOID'?'bad':a?.includes('REDUCE')?'warn':''}
function intelText(){const d=S.intel?.data||S.intel;if(!d||d.ok===false)return S.intel?.error||'Chưa có dữ liệu';for(const k of ['summary','marketSummary','overview','briefing','headline','title'])if(typeof d[k]==='string')return d[k].slice(0,500);return `Đã kết nối • ${Object.keys(d).length} trường dữ liệu`}
function dashboard(){const rs=recs(),rg=regime(),ps=pos(),pnl=ps.reduce((a,p)=>a+(p.pnl??0),0),urgent=rs.filter(r=>r.riskSeverity>=70),err=S.watch.filter(x=>!S.market[x.symbol]?.price).length;$('#view-dashboard').innerHTML=`<div class="topbar"><div><h1 class="title">Stock Radar VN</h1><div class="sub">${S.watch.length} mã trọng tâm • Risk Engine độc lập • Không tự đặt lệnh</div></div><button id="refreshBtn" class="btn primary">Cập nhật ngay</button></div><div class="grid g4"><div class="card"><div class="label">Market Regime</div><div class="metric ${rg.state==='RISK_ON'?'good':rg.state==='RISK_OFF'?'bad':'warn'}">${rg.state}</div><div class="small">${rg.score}/100 • confidence ${rg.confidence}%</div></div><div class="card"><div class="label">Portfolio P&L</div><div class="metric ${pnl>=0?'good':'bad'}">${ps.length?fmt(pnl,0):'Chưa nhập'}</div></div><div class="card"><div class="label">Risk Alerts</div><div class="metric ${urgent.length?'bad':'good'}">${urgent.length}</div></div><div class="card"><div class="label">Data Health</div><div class="metric ${err?'warn':'good'}">${S.watch.length-err}/${S.watch.length}</div><div class="small">${S.last?new Date(S.last).toLocaleString('vi-VN'):'chưa cập nhật'}</div></div></div><div class="section grid g2"><div class="card"><h2>Provider Health</h2>${(S.health?.checks||[]).map(x=>`<div class="kpiRow"><span>${esc(x.name)}</span><b class="${x.ok?'good':'bad'}">${x.ok?'ONLINE':'OFFLINE'}</b></div>`).join('')||'<div class="empty">Chưa kiểm tra</div>'}</div><div class="card"><h2>Market Intel</h2><div class="small">${esc(intelText())}</div></div></div><div class="section"><div class="card tableWrap"><table class="table"><thead><tr><th>Mã</th><th>Giá</th><th>1D</th><th>RSI</th><th>Score</th><th>Confidence</th><th>Risk</th><th>Action</th></tr></thead><tbody>${rs.map(r=>{const m=S.market[r.symbol]||{};return`<tr><td><b>${r.symbol}</b></td><td>${fmt(m.price)}</td><td>${m.changePct==null?'—':fmt(m.changePct)+'%'}</td><td>${fmt(m.indicators?.rsi14,1)}</td><td>${fmt(r.score,1)}</td><td>${r.confidence}%</td><td>${r.riskSeverity}</td><td class="${cls(r.action)}">${r.action}</td></tr>`}).join('')}</tbody></table></div></div>`;$('#refreshBtn').onclick=refresh}
function portfolio(){const ps=pos(),sw=wgt();$('#view-portfolio').innerHTML=`<div class="topbar"><div><h1 class="title">Portfolio Master</h1><div class="sub">Nhập giao dịch thật để tính giá vốn, P&L và concentration risk</div></div></div><div class="card"><div class="formGrid"><input id="ts" class="input" placeholder="Mã"><select id="tt" class="input"><option>STOCK</option><option>ETF</option></select><input id="tp" class="input" type="number" placeholder="Giá"><input id="tq" class="input" type="number" placeholder="Số lượng"><input id="tf" class="input" type="number" value="0" placeholder="Phí"><input id="tc" class="input" placeholder="Ngành"><button id="ta" class="btn primary">Lưu</button></div></div><div class="section grid g2"><div class="card"><h2>Tiền mặt: ${fmt(cash(),0)}</h2><div class="actions"><input id="ca" class="input" type="number" placeholder="Số tiền"><button id="ci" class="btn">Nạp</button><button id="co" class="btn">Rút</button></div></div><div class="card"><h2>Concentration</h2>${Object.entries(sw).map(([k,v])=>`<div class="kpiRow"><span>${esc(k)}</span><b class="${v>S.policy.maxSector?'bad':''}">${fmt(v,1)}%</b></div>`).join('')||'Chưa có vị thế'}</div></div><div class="section card tableWrap"><table class="table"><thead><tr><th>Mã</th><th>SL</th><th>Giá vốn</th><th>Giá</th><th>P&L</th><th>P&L%</th></tr></thead><tbody>${ps.map(p=>`<tr><td><b>${p.symbol}</b></td><td>${fmt(p.qty,0)}</td><td>${fmt(p.avgCost)}</td><td>${fmt(p.price)}</td><td>${fmt(p.pnl,0)}</td><td>${fmt(p.pnlPct,1)}%</td></tr>`).join('')||'<tr><td colspan="6">Chưa có giao dịch</td></tr>'}</tbody></table></div>`;$('#ta').onclick=()=>{const symbol=$('#ts').value.trim().toUpperCase(),price=+$('#tp').value,quantity=+$('#tq').value;if(!symbol||!price||!quantity)return toast('Thiếu mã, giá hoặc số lượng');S.tx.push({id:id(),symbol,type:$('#tt').value,price,quantity,fee:+$('#tf').value||0,sector:$('#tc').value||'Khác',date:new Date().toISOString()});save();render()};$('#ci').onclick=()=>cashMove(1);$('#co').onclick=()=>cashMove(-1)}
function cashMove(sign){const v=+$('#ca').value;if(v>0){S.cash.push({id:id(),amount:v*sign,timestamp:Date.now()});save();render()}}
function radar(){const rs=recs();$('#view-radar').innerHTML=`<div class="topbar"><div><h1 class="title">Stock & ETF Radar</h1><div class="sub">Dữ liệu thiếu làm giảm confidence, không bị tính 0 điểm.</div></div></div><div class="card tableWrap"><table class="table"><thead><tr><th>Mã</th><th>Fund.</th><th>Smart</th><th>Catalyst</th><th>Risk Q.</th><th>Social</th><th>Invalidation</th><th>Score</th><th>Action</th></tr></thead><tbody>${S.watch.map((x,i)=>{const r=rs.find(z=>z.symbol===x.symbol);return`<tr><td><b>${x.symbol}</b></td>${['fundamentals','smartMoney','catalyst','riskQuality','socialAdjustment'].map(k=>`<td><input class="input" type="number" data-i="${i}" data-k="${k}" value="${x.manual?.[k]??''}"></td>`).join('')}<td><input class="input" type="number" data-i="${i}" data-inv value="${x.invalidation??''}"></td><td>${fmt(r?.score,1)} (${r?.confidence||0}%)</td><td class="${cls(r?.action)}">${r?.action||'—'}</td></tr>`}).join('')}</tbody></table></div><div class="section card"><h2>Bear / Base / Bull</h2>${rs.map(r=>`<div class="small"><b>${r.symbol}</b>: Bear ${r.bear||'chưa đủ ATR'} • Base ${r.base||'chưa đủ ATR'} • Bull ${r.bull||'chưa đủ ATR'}</div>`).join('')}</div>`;document.querySelectorAll('[data-k]').forEach(el=>el.onchange=()=>{const x=S.watch[+el.dataset.i];x.manual??={};x.manual[el.dataset.k]=el.value===''?undefined:+el.value;save();render()});document.querySelectorAll('[data-inv]').forEach(el=>el.onchange=()=>{S.watch[+el.dataset.i].invalidation=el.value===''?undefined:+el.value;save();render()})}
function social(){const opts=S.sources.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');$('#view-social').innerHTML=`<div class="topbar"><div><h1 class="title">Social & Expert Intelligence</h1><div class="sub">Chỉ là tín hiệu mềm; tối đa +/-3 điểm.</div></div></div><div class="grid g2"><div class="card"><input id="sn" class="input" placeholder="Tên nguồn"><input id="su" class="input" placeholder="URL"><button id="sa" class="btn primary">Thêm nguồn</button></div><div class="card"><select id="ss" class="input"><option value="">Nguồn</option>${opts}</select><input id="sm" class="input" placeholder="Mã"><input id="st" class="input" placeholder="Luận điểm"><button id="sg" class="btn primary">Lưu tín hiệu</button></div></div><div class="section card">${S.sources.map(s=>`<div class="kpiRow"><span>${esc(s.name)}</span><span>${s.verifiedSignals||0} mẫu • ${s.verifiedSignals?fmt((s.wins||0)/s.verifiedSignals*100,0)+'%':'chưa có hit rate'}</span></div>`).join('')||'Chưa có nguồn'}</div>`;$('#sa').onclick=()=>{const n=$('#sn').value.trim();if(n){S.sources.push({id:id(),name:n,url:$('#su').value.trim(),verifiedSignals:0,wins:0,verifiable:!!$('#su').value.trim()});save();render()}};$('#sg').onclick=()=>{if($('#ss').value&&$('#sm').value&&$('#st').value){S.signals.unshift({id:id(),sourceId:$('#ss').value,symbol:$('#sm').value.toUpperCase(),thesis:$('#st').value,timestamp:Date.now(),outcome:'OPEN'});save();render()}}}
function evidence(){ $('#view-evidence').innerHTML=`<div class="topbar"><div><h1 class="title">Nguồn & Evidence</h1><div class="sub">Official trước, social sau; mọi evidence có timestamp.</div></div></div><div class="grid g2"><div class="card"><input id="es" class="input" placeholder="Mã"><input id="et" class="input" placeholder="Tiêu đề"><input id="eu" class="input" placeholder="URL"><select id="er" class="input">${[1,2,3,4,5].map(x=>`<option>${x}</option>`).join('')}</select><button id="ea" class="btn primary">Lưu</button></div><div class="card">${SOURCE_REGISTRY.map(s=>`<div class="small">Tier ${s.tier}: ${esc(s.name)}</div>`).join('')}</div></div><div class="section card">${S.evidence.map(e=>`<div class="small"><b>${e.symbol||'—'}</b> • Tier ${e.tier} • <a target="_blank" rel="noreferrer" href="${esc(e.url)}">${esc(e.title)}</a> • ${new Date(e.timestamp).toLocaleString('vi-VN')}</div>`).join('')||'Chưa có evidence thủ công'}</div>`;$('#ea').onclick=()=>{if($('#et').value&&$('#eu').value){S.evidence.unshift({id:id(),symbol:$('#es').value.toUpperCase(),title:$('#et').value,url:$('#eu').value,tier:+$('#er').value,timestamp:Date.now()});save();render()}}}
function journalView(){ $('#view-journal').innerHTML=`<div class="topbar"><div><h1 class="title">Recommendation Journal</h1><div class="sub">Snapshot không sửa lịch sử cũ.</div></div></div><div class="card tableWrap"><table class="table"><thead><tr><th>Mã</th><th>Thời điểm</th><th>Giá</th><th>Score</th><th>Risk</th><th>Action</th><th>Provider</th></tr></thead><tbody>${S.journal.map(r=>`<tr><td>${r.symbol}</td><td>${new Date(r.timestamp).toLocaleString('vi-VN')}</td><td>${fmt(r.price)}</td><td>${fmt(r.score,1)}</td><td>${r.riskSeverity}</td><td>${r.action}</td><td>${esc(r.provider)}</td></tr>`).join('')||'<tr><td colspan="7">Chưa có snapshot</td></tr>'}</tbody></table></div>`}
function settings(){ $('#view-settings').innerHTML=`<div class="topbar"><div><h1 class="title">Policy & Backup</h1></div></div><div class="grid g3">${Object.entries(S.policy).map(([k,v])=>`<div class="card"><div class="label">${k}</div><input class="input" data-p="${k}" type="number" value="${v}"></div>`).join('')}</div><div class="section grid g2"><div class="card"><button id="notify" class="btn">Bật browser alerts</button></div><div class="card"><button id="backup" class="btn primary">Xuất backup JSON</button> <label class="btn">Khôi phục<input id="restore" type="file" accept="application/json" hidden></label></div></div>`;document.querySelectorAll('[data-p]').forEach(x=>x.onchange=()=>{S.policy[x.dataset.p]=+x.value;save();render()});$('#notify').onclick=()=>Notification?.requestPermission?.();$('#backup').onclick=backup;$('#restore').onchange=e=>restore(e.target.files?.[0])}
function backup(){const data={version:'1.2',at:new Date().toISOString(),data:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k.startsWith(K))data.data[k]=localStorage.getItem(k)}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='stock-radar-backup.json';a.click()}
async function restore(f){if(!f)return;try{const j=JSON.parse(await f.text());for(const [k,v] of Object.entries(j.data||{}))if(k.startsWith(K))localStorage.setItem(k,v);location.reload()}catch{toast('Backup không hợp lệ')}}
function render(){dashboard();portfolio();radar();social();evidence();journalView();settings()}
function nav(){document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(`#view-${b.dataset.view}`).classList.add('active')})}
nav();render();if(!S.last||Date.now()-S.last>10*60*1000)refresh();setInterval(()=>{const d=new Date(),m=d.getHours()*60+d.getMinutes();if(d.getDay()>0&&d.getDay()<6&&m>=525&&m<=915)refresh()},5*60*1000);