export const DEFAULT_WATCH=[
 ['VNM','STOCK','Tiêu dùng'],['VIC','STOCK','Bất động sản'],['FPT','STOCK','Công nghệ'],['HPG','STOCK','Thép'],['MWG','STOCK','Bán lẻ'],['MBB','STOCK','Ngân hàng'],['TCB','STOCK','Ngân hàng'],['ACB','STOCK','Ngân hàng'],['CTG','STOCK','Ngân hàng'],['HDB','STOCK','Ngân hàng'],['GAS','STOCK','Dầu khí']
].map(([symbol,type,sector])=>({symbol,type,sector,manual:{}}));
export const DEFAULT_POLICY={maxSinglePosition:15,maxSector:30,etfMin:30,etfMax:50,riskOffMinCash:35,minDataConfidence:70,maxDrawdownAlert:8};
export const SOURCE_REGISTRY=[
 {tier:1,name:'HOSE/HNX/VSDC/UBCKNN',kind:'Official'},
 {tier:1,name:'Doanh nghiệp niêm yết',kind:'Issuer'},
 {tier:2,name:'Market data / CTCK data',kind:'Market/Broker'},
 {tier:3,name:'Báo chí tài chính / Research',kind:'News/Research'},
 {tier:4,name:'Chuyên gia / Social',kind:'Expert/Social'},
 {tier:5,name:'Forum / Community',kind:'Community'}
];
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null; const sma=(a,n)=>a.length>=n?avg(a.slice(-n)):null; const pct=(a,b)=>b?((a/b)-1)*100:null;
function ema(a,n){if(a.length<n)return[];const k=2/(n+1);let e=avg(a.slice(0,n));const out=[e];for(let i=n;i<a.length;i++){e=a[i]*k+e*(1-k);out.push(e)}return out}
export function indicators(points){const c=points.map(p=>p.close),v=points.map(p=>p.volume);let rsi=null;if(c.length>=15){let g=0,l=0;for(let i=c.length-14;i<c.length;i++){const d=c[i]-c[i-1];d>=0?g+=d:l-=d}rsi=l===0?100:100-(100/(1+(g/14)/(l/14)))}let atr=null;if(points.length>=15){const tr=[];for(let i=1;i<points.length;i++){const p=points[i],pc=points[i-1].close;tr.push(Math.max(p.high-p.low,Math.abs(p.high-pc),Math.abs(p.low-pc)))}atr=avg(tr.slice(-14))}const e12=ema(c,12),e26=ema(c,26);let macd=null,macdSignal=null;if(e12.length&&e26.length){const off=e12.length-e26.length,m=e26.map((x,i)=>e12[i+off]-x),sig=ema(m,9);macd=m.at(-1);macdSignal=sig.at(-1)??null}const ret=n=>c.length>n?pct(c.at(-1),c.at(-(n+1))):null;const av= v.length>=20?avg(v.slice(-20)):null;return{sma20:sma(c,20),sma50:sma(c,50),sma200:sma(c,200),rsi14:rsi,macd,macdSignal,atr14:atr,high20:points.length>=20?Math.max(...points.slice(-20).map(p=>p.high)):null,low20:points.length>=20?Math.min(...points.slice(-20).map(p=>p.low)):null,volumeRatio20:av&&av>0?v.at(-1)/av:null,ret1d:ret(1),ret5d:ret(5),ret20d:ret(20),ret60d:ret(60)} }
export function technicalScore(i,price){if(price==null)return null;let s=50,u=0;for(const ma of [i.sma20,i.sma50,i.sma200])if(ma!=null){s+=price>ma?10:-10;u++}if(i.rsi14!=null){s+=i.rsi14>=50&&i.rsi14<=70?8:i.rsi14>78?-12:i.rsi14<30?4:-2;u++}if(i.macd!=null&&i.macdSignal!=null){s+=i.macd>i.macdSignal?8:-8;u++}if(i.volumeRatio20!=null&&i.ret5d!=null){s+=i.volumeRatio20>1.4&&i.ret5d>0?8:i.volumeRatio20>2&&i.ret5d<0?-12:0;u++}return u?Math.max(0,Math.min(100,s)):null}
export const WEIGHTS={fundamentals:30,technicals:25,smartMoney:20,catalyst:15,riskQuality:10};
export function provisionalScore(input={}){const vals=Object.keys(WEIGHTS).filter(k=>Number.isFinite(input[k])).map(k=>[k,Number(input[k])]);const tw=vals.reduce((a,[k])=>a+WEIGHTS[k],0);if(!tw)return{score:null,confidence:0,missing:Object.keys(WEIGHTS)};const base=vals.reduce((a,[k,v])=>a+v*WEIGHTS[k],0)/tw;const social=Math.max(-3,Math.min(3,Number(input.socialAdjustment)||0));return{score:Math.max(0,Math.min(100,base+social)),confidence:tw,missing:Object.keys(WEIGHTS).filter(k=>!vals.some(([x])=>x===k))}}
export function riskEngine({price,entry,invalidation,i,sectorWeight,maxSector}){let severity=10;const reasons=[];if(price!=null&&invalidation!=null&&price<=invalidation){severity=Math.max(severity,90);reasons.push('Giá đã chạm/xuyên ngưỡng vô hiệu')}if(price!=null&&entry>0){const d=(price/entry-1)*100;if(d<=-12){severity=Math.max(severity,80);reasons.push(`Drawdown ${d.toFixed(1)}% từ giá vốn`)}else if(d<=-8){severity=Math.max(severity,65);reasons.push(`Drawdown ${d.toFixed(1)}% từ giá vốn`)}}if(i?.ret1d!=null&&i?.volumeRatio20!=null&&i.ret1d<=-4&&i.volumeRatio20>=2.5){severity=Math.max(severity,75);reasons.push('Giảm mạnh kèm khối lượng bất thường')}if(i?.sma50!=null&&price!=null&&price<i.sma50){severity=Math.max(severity,45);reasons.push('Giá dưới SMA50')}if(i?.rsi14!=null&&i.rsi14>80){severity=Math.max(severity,40);reasons.push('RSI quá mua')}if(sectorWeight!=null&&maxSector!=null&&sectorWeight>maxSector){severity=Math.max(severity,60);reasons.push(`Tỷ trọng ngành ${sectorWeight.toFixed(1)}% vượt policy ${maxSector}%`)}const state=severity>=85?'EXIT_REVIEW_NOW':severity>=70?'REDUCE_REVIEW_NOW':severity>=50?'HIGH_ALERT':severity>=30?'WATCH':'NORMAL';return{severity,state,reasons}}
export function actionFrom(score,confidence,risk,minConfidence=70){if(risk>=85)return'EXIT_REVIEW_NOW';if(risk>=70)return'REDUCE_REVIEW_NOW';if(score==null)return'AVOID';if(score>=80&&risk<=35&&confidence>=minConfidence)return'PRIORITY_BUY';if(confidence<40)return score>=55?'WATCH_HOLD':'AVOID';if(score>=70)return'WATCH_BUY';if(score>=55)return'WATCH_HOLD';return'AVOID'}
export function recommend(item,m,policy,entry,sectorWeight){const tech=technicalScore(m?.indicators,m?.price),f={...(item.manual||{})};if(tech!=null)f.technicals=tech;const p=provisionalScore(f);const r=riskEngine({price:m?.price,entry,invalidation:item.invalidation,i:m?.indicators,sectorWeight,maxSector:policy.maxSector});const action=actionFrom(p.score,p.confidence,r.severity,policy.minDataConfidence);const rationale=[];if(tech!=null)rationale.push(`Kỹ thuật ${tech.toFixed(0)}/100`);if(m?.indicators?.ret20d!=null)rationale.push(`20 phiên ${m.indicators.ret20d>=0?'+':''}${m.indicators.ret20d.toFixed(1)}%`);rationale.push(...r.reasons);if(p.confidence<policy.minDataConfidence)rationale.push(`Data Confidence ${p.confidence}% < policy ${policy.minDataConfidence}%`);let bear,base,bull;if(m?.price!=null&&m?.indicators?.atr14!=null){const a=m.indicators.atr14,q=m.price;bear=`${Math.max(0,q-2*a).toFixed(2)} – ${(q-a).toFixed(2)}`;base=`${(q+a).toFixed(2)} – ${(q+2*a).toFixed(2)}`;bull=`${(q+2*a).toFixed(2)} – ${(q+3.5*a).toFixed(2)}`}return{id:`${item.symbol}-${Date.now()}-${Math.random()}`,symbol:item.symbol,timestamp:Date.now(),price:m?.price??null,score:p.score==null?null:Number(p.score.toFixed(1)),confidence:p.confidence,action,riskSeverity:r.severity,riskState:r.state,rationale,missing:p.missing,invalidation:item.invalidation,bear,base,bull}}
export function buildPositions(tx,market={}){const map={};for(const t of tx){const symbol=String(t.symbol||'').toUpperCase();if(!symbol)continue;const price=Number(t.price),rawQty=Number(t.quantity),fee=Math.max(0,Number(t.fee)||0);if(!Number.isFinite(price)||price<=0||!Number.isFinite(rawQty)||rawQty===0)continue;const side=String(t.side||'').toUpperCase();const isSell=side==='SELL'||rawQty<0;const qty=Math.abs(rawQty);const x=map[symbol]??={symbol,type:t.type||'STOCK',sector:t.sector||'Khác',qty:0,basis:0,realizedPnl:0,totalFees:0,oversoldQty:0};x.type=t.type||x.type;x.sector=t.sector||x.sector;x.totalFees+=fee;if(!isSell){x.qty+=qty;x.basis+=price*qty+fee}else if(x.qty>0){const sold=Math.min(qty,x.qty),avgCost=x.basis/x.qty,removed=avgCost*sold,allocatedFee=fee*(sold/qty),proceeds=price*sold-allocatedFee;x.realizedPnl+=proceeds-removed;x.qty-=sold;x.basis=Math.max(0,x.basis-removed);if(qty>sold)x.oversoldQty+=qty-sold;if(x.qty<1e-10){x.qty=0;x.basis=0}}else{x.oversoldQty+=qty}map[symbol]=x}return Object.values(map).filter(x=>x.qty>0||x.realizedPnl!==0||x.oversoldQty>0).map(x=>{const avgCost=x.qty>0?x.basis/x.qty:null,price=x.qty>0?(market[x.symbol]?.price??null):null,value=price==null?null:price*x.qty,unrealizedPnl=value==null?null:value-x.basis;return{...x,cost:x.basis,fees:0,avgCost,price,value,pnl:unrealizedPnl,pnlPct:unrealizedPnl==null||x.basis<=0?null:unrealizedPnl/x.basis*100,unrealizedPnl}})}
export function sectorWeights(positions,cash=0){const total=positions.reduce((a,p)=>a+(p.value??p.basis??p.cost??0),0)+cash;const out={};for(const p of positions){if(p.qty<=0)continue;const val=p.value??p.basis??p.cost??0;out[p.sector]=(out[p.sector]||0)+(total?val/total*100:0)}return out}
export function marketRegime(index,universe=[]){let score=50,confidence=0,parts=[];if(index?.price!=null){let trend=50,n=0;for(const ma of [index.indicators?.sma20,index.indicators?.sma50,index.indicators?.sma200])if(ma!=null){trend+=index.price>ma?12:-12;n++}if(n){score=trend*.30+35;confidence+=30;parts.push(`Xu hướng VN-Index proxy ${Math.max(0,Math.min(100,trend)).toFixed(0)}`)}}const usable=universe.filter(x=>x?.changePct!=null);if(usable.length>=5){const b=usable.filter(x=>x.changePct>0).length/usable.length*100;score+=(b-50)*.25;confidence+=20;parts.push(`Độ rộng watchlist ${b.toFixed(0)}% tăng`)}const vols=universe.map(x=>x?.indicators?.volumeRatio20).filter(Number.isFinite);if(vols.length>=5){const v=avg(vols);score+=(Math.min(2,v)-1)*8;confidence+=15;parts.push(`Volume ratio ${v.toFixed(2)}x`)}const lead=universe.map(x=>x?.indicators?.ret20d).filter(Number.isFinite);if(lead.length>=5){const lp=lead.filter(x=>x>0).length/lead.length*100;score+=(lp-50)*.15;confidence+=15;parts.push(`Leadership proxy ${lp.toFixed(0)}%`)}if(index?.price&&index?.indicators?.atr14){const ap=index.indicators.atr14/index.price*100;score+=(2-Math.min(4,ap))*4;confidence+=10;parts.push(`ATR Index ${ap.toFixed(2)}%`)}score=Math.max(0,Math.min(100,score));return{score:Math.round(score),confidence:Math.min(90,confidence),state:score>=62?'RISK_ON':score<=38?'RISK_OFF':'NEUTRAL',parts,note:'Regime dùng watchlist làm proxy cho breadth; chưa phải độ rộng toàn thị trường.'}}
