import {ETF_UNIVERSE} from './universe.js';
import {indicators,technicalScore} from './core.js';
const K='srvn:';const fmt=(n,d=2)=>n==null||!Number.isFinite(+n)?'—':new Intl.NumberFormat('vi-VN',{maximumFractionDigits:d}).format(+n);
const get=(k,d)=>{try{const v=localStorage.getItem(K+k);return v?JSON.parse(v):structuredClone(d)}catch{return structuredClone(d)}};
async function json(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
function label(m){const i=m.indicators||{},t=technicalScore(i,m.price);if(t==null)return{action:'CHƯA ĐỦ DỮ LIỆU',score:null};if(i.sma50!=null&&m.price<i.sma50)return{action:'THEO DÕI / KHÔNG MUA ĐUỔI',score:t};if(t>=70&&i.rsi14!=null&&i.rsi14<75)return{action:'CANH MUA ETF LÕI',score:t};if(t>=55)return{action:'GIỮ / THEO DÕI',score:t};return{action:'CHƯA ƯU TIÊN',score:t}}
async function load(){const rows=await Promise.all(ETF_UNIVERSE.map(async e=>{try{const m=await json(`./data/${e.symbol}.json`);m.indicators=indicators(m.points||[]);return{...e,m,...label(m)}}catch(err){return{...e,m:{price:null},action:'CHƯA CÓ SNAPSHOT',score:null,error:String(err.message||err)}}}));render(rows)}
function render(rows=[]){const v=document.querySelector('#view-etf');if(!v)return;const p=get('policy',{etfMin:30,etfMax:50}),ok=rows.filter(x=>x.m?.price!=null).length;v.innerHTML=`<div class="topbar"><div><h1 class="title">ETF Core Radar</h1><div class="sub">Core–Satellite • mục tiêu ETF lõi ${p.etfMin??30}–${p.etfMax??50}% • không tự đặt lệnh</div></div><button id="etfRefresh" class="btn primary">Cập nhật ETF</button></div><div class="grid g3"><div class="card"><div class="label">ETF universe</div><div class="metric">${ok}/${rows.length}</div></div><div class="card"><div class="label">Canh mua lõi</div><div class="metric good">${rows.filter(x=>x.action==='CANH MUA ETF LÕI').length}</div></div><div class="card"><div class="label">Policy core</div><div class="metric">${p.etfMin??30}–${p.etfMax??50}%</div></div></div><div class="section card tableWrap"><table class="table"><thead><tr><th>Mã ETF</th><th>Chỉ số</th><th>Giá</th><th>1D</th><th>RSI</th><th>SMA20</th><th>SMA50</th><th>ATR</th><th>Technical</th><th>Hành động</th></tr></thead><tbody>${rows.map(x=>`<tr><td><b>${x.symbol}</b></td><td>${x.indexName}</td><td>${fmt(x.m?.price)}</td><td>${fmt(x.m?.changePct,2)}%</td><td>${fmt(x.m?.indicators?.rsi14,1)}</td><td>${fmt(x.m?.indicators?.sma20)}</td><td>${fmt(x.m?.indicators?.sma50)}</td><td>${fmt(x.m?.indicators?.atr14)}</td><td>${fmt(x.score,0)}</td><td><b>${x.action}</b></td></tr>`).join('')}</tbody></table></div><div class="section card"><div class="small">ETF Radar ưu tiên vai trò ổn định danh mục. Tín hiệu ETF dựa trên xu hướng/động lượng và liquidity snapshot; không dùng Fundamentals cổ phiếu để chấm ETF.</div></div>`;document.querySelector('#etfRefresh').onclick=load}
function install(){if(!document.querySelector('[data-view="etf"]')){const nav=document.querySelector('#nav'),b=document.createElement('button');b.dataset.view='etf';b.textContent='ETF Core Radar';const radar=nav.querySelector('[data-view="radar"]');radar?.after(b);const s=document.createElement('section');s.className='view';s.id='view-etf';document.querySelector('.main')?.insertBefore(s,document.querySelector('.footerNote'));b.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));s.classList.add('active');load()}}load()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
