import test from 'node:test';
import assert from 'node:assert/strict';
import {hotNewsRisk,positionSizeByRisk,etfDecision,holdingDecision} from '../decision-v2.js';
const market=(price=100)=>({price,indicators:{sma20:99,sma50:95,sma200:88,rsi14:61,atr14:2,high20:103,volumeRatio20:1.15,ret5d:2,ret20d:8,ret60d:14}});const index={price:1400,indicators:{sma20:1380,sma50:1340,sma200:1260,ret20d:3,ret60d:7}};
test('confirmed severe official news triggers veto',()=>{const x=hotNewsRisk([{title:'Doanh nghiệp bị khởi tố vụ án',source:'HOSE.vn',official:true}]);assert.equal(x.veto,true);assert.ok(x.severity>=90)});
test('position size obeys risk budget and cap',()=>{const x=positionSizeByRisk({portfolioValue:1_000_000_000,entryPrice:50_000,stopPrice:47_500,riskPct:0.8,maxPositionPct:15,lotSize:100});assert.ok(x.capital<=150_000_000);assert.ok(x.shares%100===0);assert.ok(x.shares>0)});
test('ETF decision respects buy zone',()=>{const m=market(100);m.indicators.high20=110;m.indicators.sma20=100;m.indicators.sma50=95;m.indicators.sma200=85;const d=etfDecision({market:m,indexMarket:index,peers:[m,{indicators:{ret20d:2}},{indicators:{ret20d:5}}],regime:'RISK_ON'});assert.ok(['BUY_NOW','WATCH_BUY','WATCH'].includes(d.code));if(d.code==='BUY_NOW')assert.equal(d.inZone,true)});
test('ETF below SMA200 becomes avoid',()=>{const m=market(80);m.indicators.sma20=95;m.indicators.sma50=90;m.indicators.sma200=88;m.indicators.ret5d=-6;m.indicators.volumeRatio20=2;const d=etfDecision({market:m,indexMarket:index,peers:[m],regime:'NEUTRAL'});assert.ok(d.risk>=70);assert.equal(d.code,'AVOID')});
test('held ETF uses dedicated holding recommendation',()=>{const m=market(112),p={symbol:'E1VFVN30',type:'ETF',qty:1000,avgCost:100,pnlPct:12};const d=holdingDecision({position:p,market:m,rec:{score:50,confidence:25,riskSeverity:10},plan:{},fundamentals:{score:null},flow:{score:null},indexMarket:index,peers:[m],regime:'RISK_ON'});assert.equal(d.symbol,'E1VFVN30');assert.ok(['HOLD_LONG','HOLD','TAKE_PROFIT','HOLD_REVIEW'].includes(d.code));assert.ok(d.confidence>=60)});
